/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tp2;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cacan
 */
public class cardDirector extends javax.swing.JPanel
{
    dbConnection dbcon = new dbConnection();
    private director dir;
    private Integer id;
    private String jumlah_film;

    /**
     * Creates new form PanelBook
     */
        
    public cardDirector(int id_director, String img, String nama, String jumlah_film)
    {
        initComponents();
        this.dir = new director(id_director, img, nama, jumlah_film);
        try {
            BufferedImage imageData = (BufferedImage) ImageIO.read(new File("src/assets/" + img));
            Image dimg = imageData.getScaledInstance(110,110,Image.SCALE_SMOOTH);
            imageLabel.setIcon(new javax.swing.ImageIcon(dimg));
        } catch (IOException e) {
            System.err.println("Gagal Memasang Gambar" + e.getMessage());
        }
        fieldNama.setText(nama);
        fieldJumlah.setText(jumlah_film);
        this.id = id_director;
    }
    
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();
        lblJumlahFilm = new javax.swing.JLabel();
        lblPict = new javax.swing.JLabel();
        fieldNama = new javax.swing.JLabel();
        fieldJumlah = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 246, 246));

        btnDelete.setBackground(new java.awt.Color(102, 102, 102));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(246, 246, 246));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(244, 244, 244));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblNama.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblNama.setForeground(new java.awt.Color(102, 102, 102));
        lblNama.setText("Nama :");

        lblJumlahFilm.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblJumlahFilm.setForeground(new java.awt.Color(102, 102, 102));
        lblJumlahFilm.setText("Jumlah Film :");

        lblPict.setBackground(new java.awt.Color(245, 245, 245));
        lblPict.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPict.setForeground(new java.awt.Color(102, 102, 102));
        lblPict.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPict.setText("img");

        fieldNama.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        fieldNama.setForeground(new java.awt.Color(102, 102, 102));
        fieldNama.setText("fieldNama");

        fieldJumlah.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        fieldJumlah.setForeground(new java.awt.Color(102, 102, 102));
        fieldJumlah.setText("fieldJumlah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPict, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNama))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblJumlahFilm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNama)
                            .addComponent(fieldNama))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJumlahFilm)
                            .addComponent(fieldJumlah))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)))
                    .addComponent(lblPict, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try
        {
            dbcon.stmt.execute("DELETE FROM director WHERE id_director=" + this.id.toString() + ";");
            JOptionPane.showMessageDialog(null, "Delete Berhasil!");
        } catch (SQLException e) {
            System.err.println("Delete Gagal " + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel fieldJumlah;
    private javax.swing.JLabel fieldNama;
    private javax.swing.JLabel lblJumlahFilm;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPict;
    // End of variables declaration//GEN-END:variables

    private void setCardPanel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
