/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tp2;

import java.awt.BorderLayout;
import java.sql.*;
import javax.swing.*;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author cacan
 */
public class cardFilm extends javax.swing.JPanel
{
    dbConnection dbcon = new dbConnection();
    private film mov;
    private Integer id;
    
    /**
     * Creates new form PanelBook
     */
    public cardFilm(int id_film, String img, String judul, String genre, String director, String deskripsi)
    {
        initComponents();
        
        fieldJudul.setText(judul);
        fieldGenre.setText(genre);
        fieldDir.setText(director);
        fieldRate.setText(deskripsi);
        
        ImageIcon imageIcon = new ImageIcon(img);
        
        try
        {
            BufferedImage imageData = (BufferedImage) ImageIO.read(new File("src/assets/" + img));
            Image dimg = imageData.getScaledInstance(110,110,Image.SCALE_SMOOTH);
//            imageLabel.setIcon(new javax.swing.ImageIcon(dimg));
        }
        catch (IOException e) {
            System.err.println("Gagal Upload Gambar " + e.getMessage());
        }
       
        this.id = id_film;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();
        lblGenre = new javax.swing.JLabel();
        lblPict = new javax.swing.JLabel();
        lblDirector = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        fieldJudul = new javax.swing.JLabel();
        fieldGenre = new javax.swing.JLabel();
        fieldDir = new javax.swing.JLabel();
        fieldRate = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setBackground(new java.awt.Color(246, 246, 246));

        btnDelete.setBackground(new java.awt.Color(102, 102, 102));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(246, 246, 246));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(244, 244, 244));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNama.setForeground(new java.awt.Color(102, 102, 102));
        lblNama.setText("Judul : ");

        lblGenre.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGenre.setForeground(new java.awt.Color(102, 102, 102));
        lblGenre.setText("Genre : ");

        lblPict.setBackground(new java.awt.Color(245, 245, 245));
        lblPict.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPict.setForeground(new java.awt.Color(102, 102, 102));
        lblPict.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPict.setText("img");

        lblDirector.setBackground(new java.awt.Color(102, 102, 102));
        lblDirector.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDirector.setForeground(new java.awt.Color(102, 102, 102));
        lblDirector.setText("Director : ");

        lblDesc.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(102, 102, 102));
        lblDesc.setText("Rating : ");

        fieldJudul.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        fieldJudul.setForeground(new java.awt.Color(102, 102, 102));
        fieldJudul.setText("fieldJudul");

        fieldGenre.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        fieldGenre.setForeground(new java.awt.Color(102, 102, 102));
        fieldGenre.setText("fieldGenre");

        fieldDir.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        fieldDir.setForeground(new java.awt.Color(102, 102, 102));
        fieldDir.setText("fieldDir");

        fieldRate.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        fieldRate.setForeground(new java.awt.Color(102, 102, 102));
        fieldRate.setText("fieldRate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPict, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldRate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(58, 58, 58)
                        .addComponent(btnDelete))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDirector)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldDir))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblGenre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNama)
                            .addComponent(fieldJudul))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGenre)
                            .addComponent(fieldGenre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDirector)
                            .addComponent(fieldDir))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDesc)
                            .addComponent(fieldRate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))
                        .addGap(21, 21, 21))
                    .addComponent(lblPict, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try
        {
            dbcon.stmt.execute("DELETE FROM film WHERE id_film=" + this.id.toString() + ";");
            JOptionPane.showMessageDialog(null, "Delete Berhasil!");
        } catch (SQLException e) {
            System.err.println("Delete Gagal " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
//        AddFilm inputFilm = new AddFilm(this.id, fieldJudul.getText(), fieldGenre.getText(), field.getText();
//        inputFilm.setVisible(true);
//        inputFilm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel fieldDir;
    private javax.swing.JLabel fieldGenre;
    private javax.swing.JLabel fieldJudul;
    private javax.swing.JLabel fieldRate;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPict;
    // End of variables declaration//GEN-END:variables
}
